name: Deploy PR Preview
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'Frontend/package-lock.json'
          
      - name: Install dependencies
        working-directory: ./Frontend
        run: npm ci
        
      - name: Build project
        working-directory: ./Frontend
        run: npm run build
          
      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
          
      - name: Comment PR or Save URL
        if: success()
        run: |
          if [ "${{ github.event.pull_request.head.repo.full_name }}" = "${{ github.repository }}" ]; then
            # Same repo - can comment directly
            curl -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments \
              -d '{"body":"🚀 PR Preview deployed! Check it out at: https://wallgodds-pr-${{ github.event.number }}.onrender.com"}'
          else
            # Fork PR - just echo the URL
            echo "🚀 PR Preview deployed at: https://wallgodds-pr-${{ github.event.number }}.onrender.com"
            echo "Preview URL: https://wallgodds-pr-${{ github.event.number }}.onrender.com" >> $GITHUB_STEP_SUMMARY
          fi
